add_lunch_combo carbon_huawei_phone-userdebug
add_lunch_combo carbon_huawei_phone-user

add_lunch_combo aosp_huawei_phone-userdebug
add_lunch_combo aosp_huawei_phone-user
add_lunch_combo aosp_huawei_phone-eng
